# This will tell github HOW or WHEN it should run your workflow. In my case, run on a scheduler
on: [push]

jobs:
  provisioning:
    runs-on: ubuntu-latest
    steps:
    - uses: brandon-vargas/goodbye-universe-action@v7
      env:
        test_secret: ${{ secrets.test_secret }}
