on: # This will tell github HOW or WHEN it should run your workflow. In my case, run on a scheduler
  schedule:
    # run every hour
    - cron:  '*/5 * * * *'
jobs:
  provisioning:
    runs-on: ubuntu-latest
    steps:
    - uses: brandon-vargas/goodbye-universe-action@v2
      env:
        test_secret: ${{ secrets.test_secret }}
